In [49]:
import numpy as np
import pandas as pd

In [50]:
matrix = pd.read_csv('matrix.csv')
matrix = matrix.set_index('Unnamed: 0')
matrix.head()

mini   loin  roquefort  berrie  \
Unnamed: 0                                                              
spinach-cheese-rolls                  False  False      False   False   
salmon-potato-soup-lohikeitto         False  False      False   False   
salmon-pho-cups-with-earl-grey-broth  False  False      False   False   
mushroom-chestnut-pithivier           False  False      False   False   
scrambled-eggs                        False  False      False   False   

                                      gruyére  italian  grenadine  intense  \
Unnamed: 0                                                                   
spinach-cheese-rolls                    False    False      False    False   
salmon-potato-soup-lohikeitto           False    False      False    False   
salmon-pho-cups-with-earl-grey-broth    False    False      False    False   
mushroom-chestnut-pithivier             False    False      False    False   
scrambled-eggs                          False    False      False    False   

                                      sprig   full  ...     soya  aberdeen  \
Unnamed: 0                                          ...                      
spinach-cheese-rolls                  False  False  ...    False     False   
salmon-potato-soup-lohikeitto          True  False  ...    False     False   
salmon-pho-cups-with-earl-grey-broth  False  False  ...    False     False   
mushroom-chestnut-pithivier           False  False  ...    False     False   
scrambled-eggs                        False  False  ...    False     False   

                                      maria   dont   deep  fairy  chipolata  \
Unnamed: 0                                                                    
spinach-cheese-rolls                  False  False  False  False      False   
salmon-potato-soup-lohikeitto         False  False  False  False      False   
salmon-pho-cups-with-earl-grey-broth  False  False  False  False      False   
mushroom-chestnut-pithivier           False  False  False  False      False   
scrambled-eggs                        False  False  False  False      False   

                                      higher-welfare  homemade  santa  
Unnamed: 0                                                             
spinach-cheese-rolls                           False     False  False  
salmon-potato-soup-lohikeitto                  False     False  False  
salmon-pho-cups-with-earl-grey-broth           False     False  False  
mushroom-chestnut-pithivier                    False     False  False  
scrambled-eggs                                 False     False  False  

[5 rows x 1811 columns]

In [51]:
matrixR = pd.read_csv('matrixR.csv')
matrixR = matrixR.set_index('Unnamed: 0')
matrixR.head()

user_1  user_2  user_3  user_4  user_5  \
Unnamed: 0                                                                      
20-minute-carbonara-with-peas             8.0     NaN     NaN     7.0     NaN   
Beetroot-dip                              NaN     NaN     NaN     5.0     NaN   
Christmas-ginger-and-fruitcake-recipe     NaN     NaN     NaN     NaN     NaN   
Edible-Christmas-trees                    NaN     NaN     NaN     NaN     NaN   
Gin-christmas-cocktail1                   NaN     NaN     NaN     NaN     7.0   

                                       user_6  user_7  user_8  user_9  \
Unnamed: 0                                                              
20-minute-carbonara-with-peas             NaN     NaN     NaN     NaN   
Beetroot-dip                              NaN     4.0     6.0     NaN   
Christmas-ginger-and-fruitcake-recipe     7.0     NaN     NaN     NaN   
Edible-Christmas-trees                    NaN     NaN     NaN     NaN   
Gin-christmas-cocktail1                   9.0     9.0     NaN     NaN   

                                       user_10     ...      user_9991  \
Unnamed: 0                                         ...                  
20-minute-carbonara-with-peas              NaN     ...            NaN   
Beetroot-dip                               NaN     ...            NaN   
Christmas-ginger-and-fruitcake-recipe      NaN     ...            NaN   
Edible-Christmas-trees                     7.0     ...            NaN   
Gin-christmas-cocktail1                    NaN     ...            NaN   

                                       user_9992  user_9993  user_9994  \
Unnamed: 0                                                               
20-minute-carbonara-with-peas                NaN        8.0        NaN   
Beetroot-dip                                 NaN        NaN        NaN   
Christmas-ginger-and-fruitcake-recipe        NaN        NaN        4.0   
Edible-Christmas-trees                       NaN        8.0        NaN   
Gin-christmas-cocktail1                      NaN        NaN        NaN   

                                       user_9995  user_9996  user_9997  \
Unnamed: 0                                                               
20-minute-carbonara-with-peas                5.0       10.0        NaN   
Beetroot-dip                                 4.0        4.0        NaN   
Christmas-ginger-and-fruitcake-recipe        NaN       10.0        NaN   
Edible-Christmas-trees                       NaN        NaN        5.0   
Gin-christmas-cocktail1                      6.0        NaN        NaN   

                                       user_9998  user_9999  user_10000  
Unnamed: 0                                                               
20-minute-carbonara-with-peas                NaN        NaN         NaN  
Beetroot-dip                                 NaN        NaN         NaN  
Christmas-ginger-and-fruitcake-recipe        NaN        NaN         NaN  
Edible-Christmas-trees                       NaN        6.0         NaN  
Gin-christmas-cocktail1                      NaN        7.0         NaN  

[5 rows x 10000 columns]

In [52]:
matrixR = matrixR.fillna(value=0)
matrixR.head()

user_1  user_2  user_3  user_4  user_5  \
Unnamed: 0                                                                      
20-minute-carbonara-with-peas             8.0     0.0     0.0     7.0     0.0   
Beetroot-dip                              0.0     0.0     0.0     5.0     0.0   
Christmas-ginger-and-fruitcake-recipe     0.0     0.0     0.0     0.0     0.0   
Edible-Christmas-trees                    0.0     0.0     0.0     0.0     0.0   
Gin-christmas-cocktail1                   0.0     0.0     0.0     0.0     7.0   

                                       user_6  user_7  user_8  user_9  \
Unnamed: 0                                                              
20-minute-carbonara-with-peas             0.0     0.0     0.0     0.0   
Beetroot-dip                              0.0     4.0     6.0     0.0   
Christmas-ginger-and-fruitcake-recipe     7.0     0.0     0.0     0.0   
Edible-Christmas-trees                    0.0     0.0     0.0     0.0   
Gin-christmas-cocktail1                   9.0     9.0     0.0     0.0   

                                       user_10     ...      user_9991  \
Unnamed: 0                                         ...                  
20-minute-carbonara-with-peas              0.0     ...            0.0   
Beetroot-dip                               0.0     ...            0.0   
Christmas-ginger-and-fruitcake-recipe      0.0     ...            0.0   
Edible-Christmas-trees                     7.0     ...            0.0   
Gin-christmas-cocktail1                    0.0     ...            0.0   

                                       user_9992  user_9993  user_9994  \
Unnamed: 0                                                               
20-minute-carbonara-with-peas                0.0        8.0        0.0   
Beetroot-dip                                 0.0        0.0        0.0   
Christmas-ginger-and-fruitcake-recipe        0.0        0.0        4.0   
Edible-Christmas-trees                       0.0        8.0        0.0   
Gin-christmas-cocktail1                      0.0        0.0        0.0   

                                       user_9995  user_9996  user_9997  \
Unnamed: 0                                                               
20-minute-carbonara-with-peas                5.0       10.0        0.0   
Beetroot-dip                                 4.0        4.0        0.0   
Christmas-ginger-and-fruitcake-recipe        0.0       10.0        0.0   
Edible-Christmas-trees                       0.0        0.0        5.0   
Gin-christmas-cocktail1                      6.0        0.0        0.0   

                                       user_9998  user_9999  user_10000  
Unnamed: 0                                                               
20-minute-carbonara-with-peas                0.0        0.0         0.0  
Beetroot-dip                                 0.0        0.0         0.0  
Christmas-ginger-and-fruitcake-recipe        0.0        0.0         0.0  
Edible-Christmas-trees                       0.0        6.0         0.0  
Gin-christmas-cocktail1                      0.0        7.0         0.0  

[5 rows x 10000 columns]

In [53]:
matrixR.loc["spinach-cheese-rolls"].values

array([ 0.,  0.,  9., ...,  0.,  0.,  0.])

In [54]:
matrix.loc["spinach-cheese-rolls"].values

array([False, False, False, ..., False, False, False], dtype=bool)

In [57]:
matrix.loc["spinach-cheese-rolls"].values*matrix.loc["spinach-cheese-rolls"].values

array([False, False, False, ..., False, False, False], dtype=bool)

In [58]:
np.sum(matrixR.loc["spinach-cheese-rolls"].values)

12577.0

In [59]:
np.sum(matrix.loc["spinach-cheese-rolls"].values*matrix.loc["spinach-cheese-rolls"].values)

19

In [60]:
np.sum(matrix.loc["spinach-cheese-rolls"].values)

19

In [88]:
matrixR.loc["20-minute-carbonara-with-peas"][3]

7.0

In [208]:
def distance_recipes(recipe1,recipe2,matrix):
    return (np.sum(matrix.loc[recipe1].values*matrix.loc[recipe2].values))/np.sum(matrix.loc[recipe1].values)

def average_rating(recipe1,matrixR):
    k=0
    for i in range (0,10000):
        if matrixR.loc[recipe1][i]!=0:
            k=k+1  
    return np.sum(matrixR.loc[recipe1].values)/k

In [209]:
average_rating("Beetroot-dip",matrixR)

6.9547461368653423

In [210]:
distance_recipes("spinach-cheese-rolls","spinach-cheese-rolls",matrix)

1.0

In [211]:
distance_recipes("spinach-cheese-rolls","salmon-potato-soup-lohikeitto",matrix)

0.15789473684210525

In [251]:
def rec_user(recipe1):
    aux = pd.DataFrame(index = matrix.index)
    aux['dist'] = 0.0
    aux['av_rating'] = 0.0
    for rec in matrix.index:
        aux.loc[rec]['dist'] = distance_recipes(recipe1,rec,matrix)
    df_return = aux[(aux["dist"]!=1)].sort_values(by=["dist"],ascending=False)[0:10]
    for rec in df_return.index:
        aux.loc[rec]['av_rating'] = average_rating(rec,matrixR)
    df_return['av_rating'] = aux['av_rating']
    return df_return

In [252]:
rec_user("spinach-cheese-rolls")

dist  av_rating
Unnamed: 0                                                   
cheese-spinach-bread-bake                 0.631579   6.947368
lentil-vegetable-soup-with-cheese-straws  0.631579   7.062937
cheese-vegetable-pies                     0.631579   6.975410
stilton-and-nut-bites                     0.578947   7.037844
cheese-pumpkin-biscuits                   0.578947   7.006142
courgette-cheese-loaf                     0.526316   7.020983
leek-cheese-bacon-muffins                 0.526316   7.017544
crunchy-cheese-bites                      0.526316   7.043642
bleeding-ketchup-cheese-bacon-muffins     0.526316   6.986066
hot-cross-loaf                            0.526316   6.941370

In [217]:
distance_recipes("spinach-cheese-rolls","cheese-spinach-bread-bake",matrix)

0.63157894736842102

In [218]:
distance_recipes("spinach-cheese-rolls","macaroni-cheese-with-broccoli",matrix)

0.52631578947368418